

class AppLocalization {
  static String currentLanguage = 'ko';

  static final Map<String, Map<String, String>> _localizedValues = {
    'ko': {
      "sort_name": "이름",
      "sort_date": "날짜",
      "sort_type": "형식",
      "sort_size": "크기",
      "filter_image": "이미지",
      "filter_video": "동영상",
      "filter_audio": "오디오",
      "filter_document": "문서",
      "search_hint": "검색...",
      "action_confirm": "확인",
      "action_cancel": "취소",
      "action_delete": "삭제",
      "action_select_mode": "파일 선택모드",
      "action_move": "이동",
      "action_settings": "설정",
      "action_selectAll": "전체 선택",
      "action_move_items": "파일 이동",
      "action_trash": "휴지통으로 이동",
      "action_permanent_delete": "영구 삭제",
      "action_create_folder": "폴더 생성",
      "navigation_parent_folder": "이전 폴더",
      "navigation_browse": "탐색",
      "recent_files_title": "최근에 추가된 파일",
      "moving_location_title": "이동 위치 선택",
      "items_selected": "{} 선택됨",
      "items_moved_count": "{}개 항목이 이동되었습니다.",
      "items_deleted_count": "휴지통으로 이동되었습니다.",
      "move_confirm_message": "{}개 항목 이동",
      "move_prepare": "이동 준비",
      "empty_folder": "폴더가 비어 있습니다.",
      "dialog_delete_title": "휴지통으로 이동",
      "dialog_delete_message": "선택한 {}개 항목을 휴지통으로 이동하시겠습니까?",
      "dialog_perm_delete_title": "영구 삭제",
      "dialog_perm_delete_message": "선택한 {}개 항목을 영구적으로 삭제하시겠습니까?\n이 작업은 되돌릴 수 없습니다.",
      "dialog_create_folder_title": "새 폴더 생성",
      "dialog_create_folder_hint": "폴더 이름을 입력하세요",
      "error_folder_create": "폴더 생성 중 오류가 발생했거나 이미 존재하는 이름입니다.",
      "error_folder_exists_title": "알림",
      "error_folder_exists_message": "같은 이름의 폴더가 이미 존재합니다.",
      "error_file_open": "파일을 열 수 없습니다: {}",
      "select_hint": "선택할 항목을 터치하거나 전체 선택을 누르세요.",
      "move_hint": "이동할 항목을 선택한 후 상단 이동 아이콘을 누르세요.",
      "delete_hint": "삭제할 항목을 선택한 후 상단 휴지통 아이콘을 누르세요.",
      "grid_view": "격자 보기",
      "list_view": "목록 보기",
      "home_recent_files": "최근 파일",
      "category_images": "이미지",
      "category_videos": "동영상",
      "category_audio": "오디오",
      "category_documents": "문서",
      "storage_title": "저장소",
      "storage_internal": "내장 메모리",
      "storage_downloads": "다운로드",
      "utility_title": "유틸리티",
      "utility_trash": "휴지통",
      "msg_trash_empty": "휴지통이 비어 있습니다.",
      "unit_items": "건",
      "time_just_now": "방금 전",
      "time_days_ago": "{}일 전",
      "time_hours_ago": "{}시간 전",
      "time_minutes_ago": "{}분 전",
      "move_here": "여기로 이동",
      "move_instruction": "이동할 폴더로 이동한 후 하단의 '여기로 이동'을 누르세요.",
      "settings_dark_mode": "다크 모드",
      "settings_dark_mode_test": "다크 모드 (테스트용)",
      "items_selected_count": "{} items selected",
      "msg_restored": "restored",
      "msg_deleted_perm": "permanently deleted",
      "msg_trash_emptied": "trash emptied",
      "action_empty_trash": "empty trash",
      "confirm_restore_selected": "restore {} items?",
      "confirm_delete_perm_selected": "permanently delete {} items?",
      "confirm_empty_trash": "empty trash?",
      "menu_tooltip": "menu",
      "msg_deleted_at": "deleted at {}",
    },
    'en': {
      "sort_name": "Name",
      "sort_date": "Date",
      "sort_type": "Type",
      "sort_size": "Size",
      "filter_image": "Images",
      "filter_video": "Videos",
      "filter_audio": "Audio",
      "filter_document": "Documents",
      "search_hint": "Search...",
      "action_confirm": "OK",
      "action_cancel": "Cancel",
      "action_delete": "Delete",
      "action_select_mode": "Select Mode",
      "action_move": "Move",
      "action_settings": "Settings",
      "action_selectAll": "Select All",
      "action_move_items": "Move Files",
      "action_trash": "Move to Trash",
      "action_permanent_delete": "Permanent Delete",
      "action_create_folder": "Create Folder",
      "navigation_parent_folder": "Parent Folder",
      "navigation_browse": "Browse",
      "recent_files_title": "Recent Files",
      "moving_location_title": "Select Location",
      "items_selected": "{} Selected",
      "items_moved_count": "{} items moved.",
      "items_deleted_count": "Moved to trash.",
      "move_confirm_message": "Move {} items",
      "move_prepare": "Ready to move",
      "empty_folder": "Empty Folder",
      "dialog_delete_title": "Move to Trash",
      "dialog_delete_message": "Move selected {} items to trash?",
      "dialog_perm_delete_title": "Permanent Delete",
      "dialog_perm_delete_message": "Permanently delete {} items?\nThis action cannot be undone.",
      "dialog_create_folder_title": "Create New Folder",
      "dialog_create_folder_hint": "Enter folder name",
      "error_folder_create": "Error creating folder or name already exists.",
      "error_folder_exists_title": "Alert",
      "error_folder_exists_message": "A folder with the same name already exists.",
      "error_file_open": "Cannot open file: {}",
      "select_hint": "Tap items to select or press select all.",
      "move_hint": "Select items to move then press the move icon.",
      "delete_hint": "Select items to delete then press the trash icon.",
      "grid_view": "Grid View",
      "list_view": "List View",
      "home_recent_files": "Recent Files",
      "category_images": "Images",
      "category_videos": "Videos",
      "category_audio": "Audio",
      "category_documents": "Documents",
      "storage_title": "Storage",
      "storage_internal": "Internal Storage",
      "storage_downloads": "Downloads",
      "utility_title": "Utilities",
      "utility_trash": "Trash",
      "msg_trash_empty": "Trash is empty.",
      "unit_items": "items",
      "time_just_now": "Just now",
      "time_days_ago": "{} days ago",
      "time_hours_ago": "{} hours ago",
      "time_minutes_ago": "{} minutes ago",
      "move_here": "Move here",
      "move_instruction": "Navigate to the destination folder and press 'Move here'.",
      "settings_dark_mode": "Dark Mode",
      "settings_dark_mode_test": "Dark Mode (Test)",
      "items_selected_count": "{} items selected",
      "msg_restored": "restored",
      "msg_deleted_perm": "permanently deleted",
      "msg_trash_emptied": "trash emptied",
      "action_empty_trash": "empty trash",
      "confirm_restore_selected": "restore {} items?",
      "confirm_delete_perm_selected": "permanently delete {} items?",
      "confirm_empty_trash": "empty trash?",
      "menu_tooltip": "menu",
      "msg_deleted_at": "deleted at {}",
    }
  };

  static String tr(String key, {List<String>? args, Map<String, String>? namedArgs}) {
    String value = _localizedValues[currentLanguage]?[key] ?? key;
    if (args != null) {
      for (var arg in args) {
        value = value.replaceFirst('{}', arg);
      }
    }
    if (namedArgs != null) {
      namedArgs.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }
}

extension StringExtension on String {
  String tr({List<String>? args, Map<String, String>? namedArgs}) {
    return AppLocalization.tr(this, args: args, namedArgs: namedArgs);
  }
}
